AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Method to get free tier limits.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 1

Resources:
  GetFreeTierLimitsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get-free-tier-limits/
      Handler: app.handler
      Runtime: python3.8
      Events:
         GetFreeTierLimits:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /free-tier-limits
            Method: get
  GetFreeTierLimitsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: production
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref CognitoUserPoolName
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPoolName
      ClientName: !Ref UserPoolClientName
      GenerateSecret: false


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetFreeTierLimitsApi:
    Description: "API Gateway endpoint URL for Prod stage for lambda function used to get free tier limits"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/production/free-tier-limits/"
  GetFreeTierLimitsFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt GetFreeTierLimitsFunction.Arn
  GetFreeTierLimitsIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GetFreeTierLimitsIamRole.Arn
